server:
  port: 8090
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: auth-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/SocialMedia
    username: postgres
    password: 123456789
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
rabbitmq:
  exchange-auth: auth-exchange
  registerKey: register-key
  queueRegister: register-queue
  registerMailQueue: mail-queue
  registerMailBindingKey: mail-key