server:
  port: 8085

spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: mail-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  mail:
    # sunucu olarak kullanılacak mail burada yazılmalıdır.
    # yani kayıt olurken girile mail'e aktivasyon kodu gönderecek ana mail burada yazılır.
    username: ${mail_name}
    # google account manager altında 'uygulama şifreleri' üzerinden üretilen şifredir.
    password: ${mail_pass}
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
rabbitmq:
  registerMailQueue: mail-queue