server:
  port: 8080
spring:
  zipkin:
    enabled: true
    base-url: http://localhost:9411
    service:
      name: userprofile-service
  rabbitmq:
    host: localhost
    port: 5672
    username: java7
    password: root
  data:
    mongodb:
      host: localhost
      port: 27017
      database: userprofileDB
      username: JavaUser
      password: root
jwt:
  secretkey: ${secretkey}
  audience: ${audience}
  issuer: ${issuer}
redis:
  url: ${redis-url}

rabbitmq:
  queueRegister: register-queue
  exchange: user-exchange
  queueElasticRegister: elastic-register-queue
  elasticRegisterBindingKey: register-key
  queueCreatePost: queue-create-post #rabbitle gelecek post için
